version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:1.6
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
  
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo:/data
    environment:
      - NEO4J_AUTH=neo4j/test1234

  # server:
  #   image: actor-server
  #   build: 
  #     context: ActorBackend
  #     dockerfile: ./ActorBackend/Dockerfile
  #   ports:
  #     - "4545:4545"
  #   depends_on:
  #     - mqtt
  #     - neo4j


volumes:
  neo:

networks:
  network1: