version: "3"

services:
  mqtt:
    image: emqx/nanomq
    container_name: mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
  #   deploy:
  #     limits:
  #       cpus: '0.3'
  #       memory: 500M
  #     reservartions:
  #       cpus: '0.01'
  #       memory: 200M
  
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo:/data
    environment:
      - NEO4J_AUTH=neo4j/test1234
    # deploy:
    #   limits:
    #     cpus: '0.3'
    #     memory: 500M
    #   reservartions:
    #     cpus: '0.01'
    #     memory: 200M

  # server:
  #   image: actor-server
  #   build: 
  #     context: ActorBackend
  #     dockerfile: ./ActorBackend/Dockerfile
  #   ports:
  #     - "4545:4545"
  #   depends_on:
  #     - mqtt
  #     - neo4j
  #   deploy:
  #     limits:
  #       cpus: '0.3'
  #       memory: 500M
  #     reservartions:
  #       cpus: '0.01'
  #       memory: 200M


volumes:
  neo:

networks:
  network1: