version: 3

services:
  mqtt:
    image: emqx/nanomq
    container_name: mqtt
    ports:
      - "1883:1883"
      - "8883:8883"
  
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo

volumes:
  neo:

networks:
  network1: